### ISSUE TITLE
fsautocomplete.exe crashes

### ISSUE THREAD

**Issue by johanvts** [rneatherway/emacs-fsharp-mode-bin#3]
Thanks for all your work.

It crashes every time I try to load a .fs or .fsproj. I'm on windows 10 (64bit).

**Comment by rneatherway** [comment]
Hi @johanvts, could you please get me a stack trace? Hopefully it is in `*fsharp-complete*`. If necessary load the project on the command line by running `mono fsuatocomplete.exe` (somewhere under the `.emacs.d/elpa` directory. Then load the project with `project "/path/to/project.fsproj`, which should trigger the issue.

**Comment by johanvts** [comment]
Sorry, the trace is in Danish. Hope you can still use it. It says validation of safe name failed.

[trace.txt](https://github.com/rneatherway/emacs-fsharp-mode-bin/files/233241/trace.txt)

**Comment by rneatherway** [comment]
I may have inserted the wrong version by mistake, and it still works on my machine because I have F# 3.1 installed. Can you try replacing the bundled FSharp.Core.dll with this one please: https://github.com/rneatherway/emacs-fsharp-mode-bin/blob/0d92d3f124b56fbdd091cc28cf20b4c0a0c157a4/FSharp.Core.dll

If that works I will replace it in the released version too.

**Comment by johanvts** [comment]
That fixed it. Thanks

**Comment by rneatherway** [comment]
Thanks for testing, this should end up on MELPA soon.
